/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { AdminCreateRunner } from '../models';
import type { CreateRunnerResponse } from '../models';
import type { RunnerFull } from '../models';
import type { Sandbox } from '../models';
/**
 * AdminApi - axios parameter creator
 * @export
 */
export declare const AdminApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Create runner
     * @param {AdminCreateRunner} adminCreateRunner
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminCreateRunner: (adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete runner
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminDeleteRunner: (id: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get runner by ID
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminGetRunnerById: (id: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List all runners
     * @param {string} [regionId] Filter runners by region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminListRunners: (regionId?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Recover sandbox from error state as an admin
     * @param {string} sandboxId ID of the sandbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminRecoverSandbox: (sandboxId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update runner scheduling status
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminUpdateRunnerScheduling: (id: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AdminApi - functional programming interface
 * @export
 */
export declare const AdminApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Create runner
     * @param {AdminCreateRunner} adminCreateRunner
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRunnerResponse>>;
    /**
     *
     * @summary Delete runner
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminDeleteRunner(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get runner by ID
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminGetRunnerById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunnerFull>>;
    /**
     *
     * @summary List all runners
     * @param {string} [regionId] Filter runners by region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminListRunners(regionId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RunnerFull>>>;
    /**
     *
     * @summary Recover sandbox from error state as an admin
     * @param {string} sandboxId ID of the sandbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminRecoverSandbox(sandboxId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Update runner scheduling status
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AdminApi - factory interface
 * @export
 */
export declare const AdminApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Create runner
     * @param {AdminCreateRunner} adminCreateRunner
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig): AxiosPromise<CreateRunnerResponse>;
    /**
     *
     * @summary Delete runner
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminDeleteRunner(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get runner by ID
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminGetRunnerById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<RunnerFull>;
    /**
     *
     * @summary List all runners
     * @param {string} [regionId] Filter runners by region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminListRunners(regionId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<RunnerFull>>;
    /**
     *
     * @summary Recover sandbox from error state as an admin
     * @param {string} sandboxId ID of the sandbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminRecoverSandbox(sandboxId: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Update runner scheduling status
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
};
/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export declare class AdminApi extends BaseAPI {
    /**
     *
     * @summary Create runner
     * @param {AdminCreateRunner} adminCreateRunner
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CreateRunnerResponse, any, {}>>;
    /**
     *
     * @summary Delete runner
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminDeleteRunner(id: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get runner by ID
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminGetRunnerById(id: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<RunnerFull, any, {}>>;
    /**
     *
     * @summary List all runners
     * @param {string} [regionId] Filter runners by region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminListRunners(regionId?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<RunnerFull[], any, {}>>;
    /**
     *
     * @summary Recover sandbox from error state as an admin
     * @param {string} sandboxId ID of the sandbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminRecoverSandbox(sandboxId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Update runner scheduling status
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
