/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Volume state
 * @export
 * @enum {string}
 */
export declare const VolumeState: {
    readonly CREATING: "creating";
    readonly READY: "ready";
    readonly PENDING_CREATE: "pending_create";
    readonly PENDING_DELETE: "pending_delete";
    readonly DELETING: "deleting";
    readonly DELETED: "deleted";
    readonly ERROR: "error";
};
export type VolumeState = typeof VolumeState[keyof typeof VolumeState];
