/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OrganizationRole } from './organization-role';
/**
 *
 * @export
 * @interface OrganizationInvitation
 */
export interface OrganizationInvitation {
    /**
     * Invitation ID
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'id': string;
    /**
     * Email address of the invitee
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'email': string;
    /**
     * Email address of the inviter
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'invitedBy': string;
    /**
     * Organization ID
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'organizationId': string;
    /**
     * Organization name
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'organizationName': string;
    /**
     * Expiration date of the invitation
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    'expiresAt': Date;
    /**
     * Invitation status
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'status': OrganizationInvitationStatusEnum;
    /**
     * Member role
     * @type {string}
     * @memberof OrganizationInvitation
     */
    'role': OrganizationInvitationRoleEnum;
    /**
     * Assigned roles
     * @type {Array<OrganizationRole>}
     * @memberof OrganizationInvitation
     */
    'assignedRoles': Array<OrganizationRole>;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    'createdAt': Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    'updatedAt': Date;
}
export declare const OrganizationInvitationStatusEnum: {
    readonly PENDING: "pending";
    readonly ACCEPTED: "accepted";
    readonly DECLINED: "declined";
    readonly CANCELLED: "cancelled";
};
export type OrganizationInvitationStatusEnum = typeof OrganizationInvitationStatusEnum[keyof typeof OrganizationInvitationStatusEnum];
export declare const OrganizationInvitationRoleEnum: {
    readonly OWNER: "owner";
    readonly MEMBER: "member";
};
export type OrganizationInvitationRoleEnum = typeof OrganizationInvitationRoleEnum[keyof typeof OrganizationInvitationRoleEnum];
