/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SnapshotDto } from './snapshot-dto';
/**
 *
 * @export
 * @interface PaginatedSnapshots
 */
export interface PaginatedSnapshots {
    /**
     *
     * @type {Array<SnapshotDto>}
     * @memberof PaginatedSnapshots
     */
    'items': Array<SnapshotDto>;
    /**
     *
     * @type {number}
     * @memberof PaginatedSnapshots
     */
    'total': number;
    /**
     *
     * @type {number}
     * @memberof PaginatedSnapshots
     */
    'page': number;
    /**
     *
     * @type {number}
     * @memberof PaginatedSnapshots
     */
    'totalPages': number;
}
