/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * The desired state of the sandbox
 * @export
 * @enum {string}
 */
export declare const SandboxDesiredState: {
    readonly DESTROYED: "destroyed";
    readonly STARTED: "started";
    readonly STOPPED: "stopped";
    readonly RESIZED: "resized";
    readonly ARCHIVED: "archived";
};
export type SandboxDesiredState = typeof SandboxDesiredState[keyof typeof SandboxDesiredState];
