/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiKeyResponse
 */
export interface ApiKeyResponse {
    /**
     * The name of the API key
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'name': string;
    /**
     * The API key value
     * @type {string}
     * @memberof ApiKeyResponse
     */
    'value': string;
    /**
     * When the API key was created
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    'createdAt': Date;
    /**
     * The list of organization resource permissions assigned to the API key
     * @type {Array<string>}
     * @memberof ApiKeyResponse
     */
    'permissions': Array<ApiKeyResponsePermissionsEnum>;
    /**
     * When the API key expires
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    'expiresAt': Date | null;
}
export declare const ApiKeyResponsePermissionsEnum: {
    readonly WRITE_REGISTRIES: "write:registries";
    readonly DELETE_REGISTRIES: "delete:registries";
    readonly WRITE_SNAPSHOTS: "write:snapshots";
    readonly DELETE_SNAPSHOTS: "delete:snapshots";
    readonly WRITE_SANDBOXES: "write:sandboxes";
    readonly DELETE_SANDBOXES: "delete:sandboxes";
    readonly READ_VOLUMES: "read:volumes";
    readonly WRITE_VOLUMES: "write:volumes";
    readonly DELETE_VOLUMES: "delete:volumes";
    readonly WRITE_REGIONS: "write:regions";
    readonly DELETE_REGIONS: "delete:regions";
    readonly READ_RUNNERS: "read:runners";
    readonly WRITE_RUNNERS: "write:runners";
    readonly DELETE_RUNNERS: "delete:runners";
    readonly READ_AUDIT_LOGS: "read:audit_logs";
};
export type ApiKeyResponsePermissionsEnum = typeof ApiKeyResponsePermissionsEnum[keyof typeof ApiKeyResponsePermissionsEnum];
