async function QuickJSRaw(moduleArg={}){var moduleRtn;var d=moduleArg,aa=!!globalThis.window,f=!!globalThis.WorkerGlobalScope,m=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(m){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}function r(a){a={log:a||function(){}};for(const c of r.gb)c(a);return d.quickJSEmscriptenExtensions=a}r.gb=[];d.quickjsEmscriptenInit=r;r.gb.push(a=>{a.getWasmMemory=function(){return t}});
var w="./this.program",x=(a,c)=>{throw c;},y=import.meta.url,z="",A,B;
if(m){var fs=require("node:fs");y.startsWith("file:")&&(z=require("node:path").dirname(require("node:url").fileURLToPath(y))+"/");B=a=>{a=C(a)?new URL(a):a;return fs.readFileSync(a)};A=async a=>{a=C(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(w=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);x=(a,c)=>{process.exitCode=a;throw c;}}else if(aa||f){try{z=(new URL(".",y)).href}catch{}f&&(B=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";
c.send(null);return new Uint8Array(c.response)});A=async a=>{if(C(a))return new Promise((b,e)=>{var g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?b(g.response):e(g.status)};g.onerror=e;g.send(null)});var c=await fetch(a,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+" : "+c.url);}}
var ba=console.log.bind(console),D=console.error.bind(console),E,F=!1,G,C=a=>a.startsWith("file://"),ca,da,ea,H,I,J,fa,ha=!1;function ia(){var a=t.buffer;d.HEAP8=ea=new Int8Array(a);new Int16Array(a);d.HEAPU8=H=new Uint8Array(a);new Uint16Array(a);I=new Int32Array(a);J=new Uint32Array(a);new Float32Array(a);new Float64Array(a);fa=new BigInt64Array(a);new BigUint64Array(a)}
function K(a){d.onAbort?.(a);a="Aborted("+a+")";D(a);F=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");da?.(a);throw a;}var L;async function ja(a){if(!E)try{var c=await A(a);return new Uint8Array(c)}catch{}if(a==L&&E)a=new Uint8Array(E);else if(B)a=B(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ka(a,c){try{var b=await ja(a);return await WebAssembly.instantiate(b,c)}catch(e){D(`failed to asynchronously prepare wasm: ${e}`),K(e)}}async function la(a){var c=L;if(!E&&!C(c)&&!m)try{var b=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){D(`wasm streaming compile failed: ${e}`),D("falling back to ArrayBuffer instantiation")}return ka(c,a)}
class M{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ma=a=>{for(;0<a.length;)a.shift()(d)},na=[],oa=[],pa=()=>{var a=d.preRun.shift();oa.push(a)},N=!0,t,qa=new TextDecoder,ra=(a,c,b,e)=>{b=c+b;if(e)return b;for(;a[c]&&!(c>=b);)++c;return c},O=(a,c,b)=>a?qa.decode(H.subarray(a,ra(H,a,c,b))):"",P=0,sa=[0,31,60,91,121,152,182,213,244,274,305,335],ta=[0,31,59,90,120,151,181,212,243,273,304,334],Q={},ua=a=>{G=a;N||0<P||(d.onExit?.(a),F=!0);x(a,new M(a))},R=a=>{if(!F)try{return a()}catch(c){c instanceof M||"unwind"==c||x(1,c)}finally{if(!(N||0<P))try{G=
a=G,ua(a)}catch(c){c instanceof M||"unwind"==c||x(1,c)}}},S=(a,c,b)=>{var e=H;if(!(0<b))return 0;var g=c;b=c+b-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(c>=b)break;e[c++]=k}else if(2047>=k){if(c+1>=b)break;e[c++]=192|k>>6;e[c++]=128|k&63}else if(65535>=k){if(c+2>=b)break;e[c++]=224|k>>12;e[c++]=128|k>>6&63;e[c++]=128|k&63}else{if(c+3>=b)break;e[c++]=240|k>>18;e[c++]=128|k>>12&63;e[c++]=128|k>>6&63;e[c++]=128|k&63;h++}}e[c]=0;return c-g},T={},va=()=>{if(!U){var a={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:w||"./this.program"},c;for(c in T)void 0===T[c]?delete a[c]:a[c]=T[c];var b=[];for(c in a)b.push(`${c}=${a[c]}`);U=b}return U},U,V=a=>{for(var c=0,b=0;b<a.length;++b){var e=a.charCodeAt(b);127>=e?c++:2047>=e?c+=2:55296<=e&&57343>=e?(c+=4,++b):c+=3}return c},xa=[null,[],[]],W=a=>{try{a()}catch(c){K(c)}};
function ya(a){var c=(...b)=>{X.Ta.push(a);try{return a(...b)}finally{F||(X.Ta.pop(),X.Ra&&X.state===X.Sa.ab&&0===X.Ta.length&&(X.state=X.Sa.Va,W(za),"undefined"!=typeof Fibers&&Fibers.pb()))}};X.eb.set(a,c);return c}function Aa(){return new Promise((a,c)=>{X.Xa={resolve:a,reject:c}})}function Ba(){var a=Ca(12+X.Wa),c=a+12,b=X.Wa;J[a>>2]=c;J[a+4>>2]=c+b;c=X.Ta[0];X.Ya.has(c)||(b=X.hb++,X.Ya.set(c,b),X.bb.set(b,c));c=X.Ya.get(c);I[a+8>>2]=c;return a}
function Da(){var a=X.bb.get(I[X.Ra+8>>2]);a=X.eb.get(a);return R(a)}
var X={mb(a){var c=/^(qts_host_call_function|qts_host_load_module_source|qts_host_normalize_module|invoke_.*|__asyncjs__.*)$/;for(let [b,e]of Object.entries(a))"function"==typeof e&&(e.nb||c.test(b))},Sa:{Va:0,ab:1,Za:2,kb:3},state:0,Wa:81920,Ra:null,fb:0,Ta:[],Ya:new Map,bb:new Map,eb:new Map,hb:0,Xa:null,jb:[],Ua(a){if(!F){if(X.state===X.Sa.Va){var c=!1,b=!1;a((e=0)=>{if(!F&&(X.fb=e,c=!0,b)){X.state=X.Sa.Za;W(()=>Ea(X.Ra));"undefined"!=typeof MainLoop&&MainLoop.ib&&MainLoop.resume();e=!1;try{var g=
Da()}catch(p){g=p,e=!0}var h=!1;if(!X.Ra){var k=X.Xa;k&&(X.Xa=null,(e?k.reject:k.resolve)(g),h=!0)}if(e&&!h)throw g;}});b=!0;c||(X.state=X.Sa.ab,X.Ra=Ba(),"undefined"!=typeof MainLoop&&MainLoop.ib&&MainLoop.pause(),W(()=>Fa(X.Ra)))}else X.state===X.Sa.Za?(X.state=X.Sa.Va,W(Ga),Ha(X.Ra),X.Ra=null,X.jb.forEach(R)):K(`invalid state: ${X.state}`);return X.fb}},lb:a=>X.Ua(async c=>{c(await a())})},Ka=(a,c,b,e,g)=>{function h(l){--P;0!==u&&Ia(u);return"string"===c?O(l):"boolean"===c?!!l:l}var k={string:l=>
{var v=0;if(null!==l&&void 0!==l&&0!==l){v=V(l)+1;var wa=Y(v);S(l,wa,v);v=wa}return v},array:l=>{var v=Y(l.length);ea.set(l,v);return v}};a=d["_"+a];var p=[],u=0;if(e)for(var n=0;n<e.length;n++){var q=k[b[n]];q?(0===u&&(u=Ja()),p[n]=q(e[n])):p[n]=e[n]}b=X.Ra;e=a(...p);g=g?.async;P+=1;if(X.Ra!=b)return Aa().then(h);e=h(e);return g?Promise.resolve(e):e};d.wasmMemory?t=d.wasmMemory:t=new WebAssembly.Memory({initial:(d.INITIAL_MEMORY||16777216)/65536,maximum:32768});ia();d.noExitRuntime&&(N=d.noExitRuntime);
d.print&&(ba=d.print);d.printErr&&(D=d.printErr);d.wasmBinary&&(E=d.wasmBinary);d.thisProgram&&(w=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.cwrap=(a,c,b,e)=>{var g=!b||b.every(h=>"number"===h||"boolean"===h);return"string"!==c&&g&&!e?d["_"+a]:(...h)=>Ka(a,c,b,h,e)};d.UTF8ToString=O;d.stringToUTF8=(a,c,b)=>S(a,c,b);d.lengthBytesUTF8=V;d.Asyncify=X;
var Ca,Ha,La,Ia,Y,Ja,dynCall_iii,dynCall_vii,dynCall_vi,Fa,za,Ea,Ga,Ma={b:(a,c,b,e)=>K(`Assertion failed: ${O(a)}, at: `+[c?O(c):"unknown filename",b,e?O(e):"unknown function"]),r:()=>K(""),l:()=>{N=!1;P=0},m:function(a,c){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);I[c>>2]=a.getSeconds();I[c+4>>2]=a.getMinutes();I[c+8>>2]=a.getHours();I[c+12>>2]=a.getDate();I[c+16>>2]=a.getMonth();I[c+20>>2]=a.getFullYear()-1900;I[c+24>>2]=a.getDay();var b=a.getFullYear();I[c+28>>2]=
(0!==b%4||0===b%100&&0!==b%400?ta:sa)[a.getMonth()]+a.getDate()-1|0;I[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();I[c+32>>2]=(b!=e&&a.getTimezoneOffset()==Math.min(e,b))|0},i:(a,c)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!c)return 0;var b=setTimeout(()=>{delete Q[a];R(()=>La(a,performance.now()))},c);Q[a]={id:b,ob:c};return 0},n:(a,c,b,e)=>{var g=(new Date).getFullYear(),h=(new Date(g,0,
1)).getTimezoneOffset();g=(new Date(g,6,1)).getTimezoneOffset();J[a>>2]=60*Math.max(h,g);I[c>>2]=Number(h!=g);c=k=>{var p=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(p/60)).padStart(2,"0")}${String(p%60).padStart(2,"0")}`};a=c(h);c=c(g);g<h?(S(a,b,17),S(c,e,17)):(S(a,e,17),S(c,b,17))},q:function(a,c,b){if(!(0<=a&&3>=a))return 28;fa[b>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},p:()=>Date.now(),k:a=>{var c=H.length;a>>>=0;if(2147483648<a)return!1;for(var b=
1;4>=b;b*=2){var e=c*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-t.buffer.byteLength+65535)/65536|0;try{t.grow(e);ia();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},d:(a,c)=>{var b=0,e=0,g;for(g of va()){var h=c+b;J[a+e>>2]=h;b+=S(g,h,Infinity)+1;e+=4}return 0},e:(a,c)=>{var b=va();J[a>>2]=b.length;a=0;for(var e of b)a+=V(e)+1;J[c>>2]=a;return 0},c:()=>52,o:function(){return 70},t:(a,c,b,e)=>{for(var g=0,h=0;h<b;h++){var k=J[c>>2],
p=J[c+4>>2];c+=8;for(var u=0;u<p;u++){var n=a,q=H[k+u],l=xa[n];0===q||10===q?(n=1===n?ba:D,q=ra(l,0),q=qa.decode(l.buffer?l.subarray(0,q):new Uint8Array(l.slice(0,q))),n(q),l.length=0):l.push(q)}g+=p}J[e>>2]=g;return 0},a:t,s:ua,j:function(a,c,b,e,g){return d.callbacks.callFunction({handleSleep:X.Ua},a,c,b,e,g)},h:function(a){return d.callbacks.shouldInterrupt(void 0,a)},g:function(a,c,b){const e={handleSleep:X.Ua};b=O(b);return d.callbacks.loadModuleSource(e,a,c,b)},f:function(a,c,b,e){const g={handleSleep:X.Ua};
b=O(b);e=O(e);return d.callbacks.normalizeModule(g,a,c,b,e)},u:function(a,c){d.callbacks.freeHostRef(void 0,a,c)},v:function(a,c){X.Wa=a||c}},Z;
Z=await (async function(){function a(b){var e=Z=b.exports;b={};for(let [g,h]of Object.entries(e))"function"==typeof h?(e=ya(h),b[g]=e):b[g]=h;b=Z=b;Ca=d._malloc=b.x;d._QTS_Throw=b.y;d._QTS_NewError=b.z;d._QTS_RuntimeSetMemoryLimit=b.A;d._QTS_RuntimeComputeMemoryUsage=b.B;d._QTS_RuntimeDumpMemoryUsage=b.C;d._QTS_RecoverableLeakCheck=b.D;d._QTS_BuildIsSanitizeLeak=b.E;d._QTS_RuntimeSetMaxStackSize=b.F;d._QTS_GetUndefined=b.G;d._QTS_GetNull=b.H;d._QTS_GetFalse=b.I;d._QTS_GetTrue=b.J;d._QTS_NewHostRef=
b.K;d._QTS_GetHostRefId=b.L;d._QTS_NewRuntime=b.M;d._QTS_FreeRuntime=b.N;Ha=d._free=b.O;d._QTS_NewContext=b.P;d._QTS_FreeContext=b.Q;d._QTS_FreeValuePointer=b.R;d._QTS_FreeValuePointerRuntime=b.S;d._QTS_FreeVoidPointer=b.T;d._QTS_FreeCString=b.U;d._QTS_DupValuePointer=b.V;d._QTS_NewObject=b.W;d._QTS_NewObjectProto=b.X;d._QTS_NewArray=b.Y;d._QTS_NewArrayBuffer=b.Z;d._QTS_NewFloat64=b._;d._QTS_GetFloat64=b.$;d._QTS_NewString=b.aa;d._QTS_GetString=b.ba;d._QTS_GetArrayBuffer=b.ca;d._QTS_GetArrayBufferLength=
b.da;d._QTS_NewSymbol=b.ea;d._QTS_GetSymbolDescriptionOrKey=b.fa;d._QTS_IsGlobalSymbol=b.ga;d._QTS_IsJobPending=b.ha;d._QTS_ExecutePendingJob=b.ia;d._QTS_GetProp=b.ja;d._QTS_GetPropNumber=b.ka;d._QTS_SetProp=b.la;d._QTS_DefineProp=b.ma;d._QTS_GetOwnPropertyNames=b.na;d._QTS_Call=b.oa;d._QTS_ResolveException=b.pa;d._QTS_Dump=b.qa;d._QTS_Eval=b.ra;d._QTS_GetModuleNamespace=b.sa;d._QTS_Typeof=b.ta;d._QTS_GetLength=b.ua;d._QTS_IsEqual=b.va;d._QTS_GetGlobalObject=b.wa;d._QTS_NewPromiseCapability=b.xa;
d._QTS_PromiseState=b.ya;d._QTS_PromiseResult=b.za;d._QTS_TestStringArg=b.Aa;d._QTS_GetDebugLogEnabled=b.Ba;d._QTS_SetDebugLogEnabled=b.Ca;d._QTS_BuildIsDebug=b.Da;d._QTS_BuildIsAsyncify=b.Ea;d._QTS_NewFunction=b.Fa;d._QTS_ArgvGetJSValueConstPointer=b.Ga;d._QTS_RuntimeEnableInterruptHandler=b.Ha;d._QTS_RuntimeDisableInterruptHandler=b.Ia;d._QTS_RuntimeEnableModuleLoader=b.Ja;d._QTS_RuntimeDisableModuleLoader=b.Ka;d._QTS_bjson_encode=b.La;d._QTS_bjson_decode=b.Ma;La=b.Na;Ia=b.Oa;Y=b.Pa;Ja=b.Qa;dynCall_iii=
b.$a;dynCall_vii=b.cb;dynCall_vi=b.rb;Fa=b.sb;za=b.tb;Ea=b.ub;Ga=b.vb;return Z}var c={a:Ma};if(d.instantiateWasm)return new Promise(b=>{d.instantiateWasm(c,(e,g)=>{b(a(e,g))})});L??=d.locateFile?d.locateFile?d.locateFile("emscripten-module.wasm",z):z+"emscripten-module.wasm":(new URL("emscripten-module.wasm",import.meta.url)).href;return a((await la(c)).instance)}());
(function(){function a(){d.calledRun=!0;if(!F){ha=!0;Z.w();ca?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var c=d.postRun.shift();na.push(c)}ma(na)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)pa();ma(oa);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();ha?moduleRtn=d:moduleRtn=new Promise((a,c)=>{ca=a;da=c});
;return moduleRtn}export default QuickJSRaw;
