/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileStatus } from './file-status';
/**
 *
 * @export
 * @interface GitStatus
 */
export interface GitStatus {
    /**
     *
     * @type {string}
     * @memberof GitStatus
     */
    'currentBranch': string;
    /**
     *
     * @type {Array<FileStatus>}
     * @memberof GitStatus
     */
    'fileStatus': Array<FileStatus>;
    /**
     *
     * @type {number}
     * @memberof GitStatus
     */
    'ahead'?: number;
    /**
     *
     * @type {number}
     * @memberof GitStatus
     */
    'behind'?: number;
    /**
     *
     * @type {boolean}
     * @memberof GitStatus
     */
    'branchPublished'?: boolean;
}
