/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateSandboxStateDto
 */
export interface UpdateSandboxStateDto {
    /**
     * The new state for the sandbox
     * @type {string}
     * @memberof UpdateSandboxStateDto
     */
    'state': UpdateSandboxStateDtoStateEnum;
    /**
     * Optional error message when reporting an error state
     * @type {string}
     * @memberof UpdateSandboxStateDto
     */
    'errorReason'?: string;
    /**
     * Whether the sandbox is recoverable
     * @type {boolean}
     * @memberof UpdateSandboxStateDto
     */
    'recoverable'?: boolean;
}
export declare const UpdateSandboxStateDtoStateEnum: {
    readonly CREATING: "creating";
    readonly RESTORING: "restoring";
    readonly DESTROYED: "destroyed";
    readonly DESTROYING: "destroying";
    readonly STARTED: "started";
    readonly STOPPED: "stopped";
    readonly STARTING: "starting";
    readonly STOPPING: "stopping";
    readonly ERROR: "error";
    readonly BUILD_FAILED: "build_failed";
    readonly PENDING_BUILD: "pending_build";
    readonly BUILDING_SNAPSHOT: "building_snapshot";
    readonly UNKNOWN: "unknown";
    readonly PULLING_SNAPSHOT: "pulling_snapshot";
    readonly ARCHIVED: "archived";
    readonly ARCHIVING: "archiving";
    readonly RESIZING: "resizing";
};
export type UpdateSandboxStateDtoStateEnum = typeof UpdateSandboxStateDtoStateEnum[keyof typeof UpdateSandboxStateDtoStateEnum];
