var QuickJSRaw=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var d=moduleArg;function f(a){a={log:a||function(){}};for(const c of f.eb)c(a);return d.quickJSEmscriptenExtensions=a}f.eb=[];d.quickjsEmscriptenInit=f;f.eb.push(a=>{a.getWasmMemory=function(){return m}});var r="./this.program",t="",w;try{t=(new URL(".",_scriptName)).href}catch{}w=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var x=console.log.bind(console),y=console.error.bind(console),z,A=!1,B,C,D,E,F,G,H,I=!1;
function J(){var a=m.buffer;d.HEAP8=E=new Int8Array(a);new Int16Array(a);d.HEAPU8=F=new Uint8Array(a);new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function K(a){d.onAbort?.(a);a="Aborted("+a+")";y(a);A=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");D?.(a);throw a;}var L;
async function aa(a){if(!z)try{var c=await w(a);return new Uint8Array(c)}catch{}if(a==L&&z)a=new Uint8Array(z);else throw"both async and sync fetching of the wasm failed";return a}async function ba(a,c){try{var b=await aa(a);return await WebAssembly.instantiate(b,c)}catch(e){y(`failed to asynchronously prepare wasm: ${e}`),K(e)}}
async function ca(a){var c=L;if(!z)try{var b=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){y(`wasm streaming compile failed: ${e}`),y("falling back to ArrayBuffer instantiation")}return ba(c,a)}class M{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var da=a=>{for(;0<a.length;)a.shift()(d)},ea=[],fa=[],ha=()=>{var a=d.preRun.shift();fa.push(a)},N=!0,m,ia=new TextDecoder,ja=(a,c,b,e)=>{b=c+b;if(e)return b;for(;a[c]&&!(c>=b);)++c;return c},O=(a,c,b)=>a?ia.decode(F.subarray(a,ja(F,a,c,b))):"",P=0,ka=[0,31,60,91,121,152,182,213,244,274,305,335],la=[0,31,59,90,120,151,181,212,243,273,304,334],Q={},ma=a=>{if(!(a instanceof M||"unwind"==a))throw a;},na=a=>{B=a;N||0<P||(d.onExit?.(a),A=!0);throw new M(a);},R=a=>{if(!A)try{return a()}catch(c){ma(c)}finally{if(!(N||
0<P))try{B=a=B,na(a)}catch(c){ma(c)}}},S=(a,c,b)=>{var e=F;if(!(0<b))return 0;var g=c;b=c+b-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(c>=b)break;e[c++]=k}else if(2047>=k){if(c+1>=b)break;e[c++]=192|k>>6;e[c++]=128|k&63}else if(65535>=k){if(c+2>=b)break;e[c++]=224|k>>12;e[c++]=128|k>>6&63;e[c++]=128|k&63}else{if(c+3>=b)break;e[c++]=240|k>>18;e[c++]=128|k>>12&63;e[c++]=128|k>>6&63;e[c++]=128|k&63;h++}}e[c]=0;return c-g},T={},oa=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",
PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:r||"./this.program"},c;for(c in T)void 0===T[c]?delete a[c]:a[c]=T[c];var b=[];for(c in a)b.push(`${c}=${a[c]}`);U=b}return U},U,V=a=>{for(var c=0,b=0;b<a.length;++b){var e=a.charCodeAt(b);127>=e?c++:2047>=e?c+=2:55296<=e&&57343>=e?(c+=4,++b):c+=3}return c},pa=[null,[],[]],W=a=>{try{a()}catch(c){K(c)}};
function ra(a){var c=(...b)=>{X.Sa.push(a);try{return a(...b)}finally{A||(X.Sa.pop(),X.Qa&&X.state===X.Ra.Za&&0===X.Sa.length&&(X.state=X.Ra.Ua,W(sa),"undefined"!=typeof Fibers&&Fibers.nb()))}};X.ab.set(a,c);return c}function ta(){return new Promise((a,c)=>{X.Wa={resolve:a,reject:c}})}function ua(){var a=va(12+X.Va),c=a+12,b=X.Va;H[a>>2]=c;H[a+4>>2]=c+b;c=X.Sa[0];X.Xa.has(c)||(b=X.fb++,X.Xa.set(c,b),X.$a.set(b,c));c=X.Xa.get(c);G[a+8>>2]=c;return a}
function wa(){var a=X.$a.get(G[X.Qa+8>>2]);a=X.ab.get(a);return R(a)}
var X={kb(a){var c=/^(qts_host_call_function|qts_host_load_module_source|qts_host_normalize_module|invoke_.*|__asyncjs__.*)$/;for(let [b,e]of Object.entries(a))"function"==typeof e&&(e.lb||c.test(b))},Ra:{Ua:0,Za:1,Ya:2,ib:3},state:0,Va:81920,Qa:null,cb:0,Sa:[],Xa:new Map,$a:new Map,ab:new Map,fb:0,Wa:null,hb:[],Ta(a){if(!A){if(X.state===X.Ra.Ua){var c=!1,b=!1;a((e=0)=>{if(!A&&(X.cb=e,c=!0,b)){X.state=X.Ra.Ya;W(()=>xa(X.Qa));"undefined"!=typeof MainLoop&&MainLoop.gb&&MainLoop.resume();e=!1;try{var g=
wa()}catch(p){g=p,e=!0}var h=!1;if(!X.Qa){var k=X.Wa;k&&(X.Wa=null,(e?k.reject:k.resolve)(g),h=!0)}if(e&&!h)throw g;}});b=!0;c||(X.state=X.Ra.Za,X.Qa=ua(),"undefined"!=typeof MainLoop&&MainLoop.gb&&MainLoop.pause(),W(()=>ya(X.Qa)))}else X.state===X.Ra.Ya?(X.state=X.Ra.Ua,W(za),Aa(X.Qa),X.Qa=null,X.hb.forEach(R)):K(`invalid state: ${X.state}`);return X.cb}},jb:a=>X.Ta(async c=>{c(await a())})},Da=(a,c,b,e,g)=>{function h(l){--P;0!==u&&Ba(u);return"string"===c?O(l):"boolean"===c?!!l:l}var k={string:l=>
{var v=0;if(null!==l&&void 0!==l&&0!==l){v=V(l)+1;var qa=Y(v);S(l,qa,v);v=qa}return v},array:l=>{var v=Y(l.length);E.set(l,v);return v}};a=d["_"+a];var p=[],u=0;if(e)for(var n=0;n<e.length;n++){var q=k[b[n]];q?(0===u&&(u=Ca()),p[n]=q(e[n])):p[n]=e[n]}b=X.Qa;e=a(...p);g=g?.async;P+=1;if(X.Qa!=b)return ta().then(h);e=h(e);return g?Promise.resolve(e):e};d.wasmMemory?m=d.wasmMemory:m=new WebAssembly.Memory({initial:(d.INITIAL_MEMORY||16777216)/65536,maximum:32768});J();d.noExitRuntime&&(N=d.noExitRuntime);
d.print&&(x=d.print);d.printErr&&(y=d.printErr);d.wasmBinary&&(z=d.wasmBinary);d.thisProgram&&(r=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.cwrap=(a,c,b,e)=>{var g=!b||b.every(h=>"number"===h||"boolean"===h);return"string"!==c&&g&&!e?d["_"+a]:(...h)=>Da(a,c,b,h,e)};d.UTF8ToString=O;d.stringToUTF8=(a,c,b)=>S(a,c,b);d.lengthBytesUTF8=V;d.Asyncify=X;
var va,Aa,Ea,Ba,Y,Ca,dynCall_iii,dynCall_vii,dynCall_vi,ya,sa,xa,za,Fa={b:(a,c,b,e)=>K(`Assertion failed: ${O(a)}, at: `+[c?O(c):"unknown filename",b,e?O(e):"unknown function"]),q:()=>K(""),l:()=>{N=!1;P=0},m:function(a,c){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);G[c>>2]=a.getSeconds();G[c+4>>2]=a.getMinutes();G[c+8>>2]=a.getHours();G[c+12>>2]=a.getDate();G[c+16>>2]=a.getMonth();G[c+20>>2]=a.getFullYear()-1900;G[c+24>>2]=a.getDay();var b=a.getFullYear();G[c+28>>2]=
(0!==b%4||0===b%100&&0!==b%400?la:ka)[a.getMonth()]+a.getDate()-1|0;G[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();G[c+32>>2]=(b!=e&&a.getTimezoneOffset()==Math.min(e,b))|0},j:(a,c)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!c)return 0;var b=setTimeout(()=>{delete Q[a];R(()=>Ea(a,performance.now()))},c);Q[a]={id:b,mb:c};return 0},n:(a,c,b,e)=>{var g=(new Date).getFullYear(),h=(new Date(g,0,
1)).getTimezoneOffset();g=(new Date(g,6,1)).getTimezoneOffset();H[a>>2]=60*Math.max(h,g);G[c>>2]=Number(h!=g);c=k=>{var p=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(p/60)).padStart(2,"0")}${String(p%60).padStart(2,"0")}`};a=c(h);c=c(g);g<h?(S(a,b,17),S(c,e,17)):(S(a,e,17),S(c,b,17))},p:()=>Date.now(),k:a=>{var c=F.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=c*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-m.buffer.byteLength+
65535)/65536|0;try{m.grow(e);J();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},d:(a,c)=>{var b=0,e=0,g;for(g of oa()){var h=c+b;H[a+e>>2]=h;b+=S(g,h,Infinity)+1;e+=4}return 0},e:(a,c)=>{var b=oa();H[a>>2]=b.length;a=0;for(var e of b)a+=V(e)+1;H[c>>2]=a;return 0},c:()=>52,o:function(){return 70},s:(a,c,b,e)=>{for(var g=0,h=0;h<b;h++){var k=H[c>>2],p=H[c+4>>2];c+=8;for(var u=0;u<p;u++){var n=a,q=F[k+u],l=pa[n];0===q||10===q?(n=1===n?x:y,q=ja(l,0),q=ia.decode(l.buffer?l.subarray(0,q):new Uint8Array(l.slice(0,
q))),n(q),l.length=0):l.push(q)}g+=p}H[e>>2]=g;return 0},a:m,r:na,i:function(a,c,b,e,g){return d.callbacks.callFunction({handleSleep:X.Ta},a,c,b,e,g)},h:function(a){return d.callbacks.shouldInterrupt(void 0,a)},g:function(a,c,b){const e={handleSleep:X.Ta};b=O(b);return d.callbacks.loadModuleSource(e,a,c,b)},f:function(a,c,b,e){const g={handleSleep:X.Ta};b=O(b);e=O(e);return d.callbacks.normalizeModule(g,a,c,b,e)},t:function(a,c){d.callbacks.freeHostRef(void 0,a,c)},u:function(a,c){X.Va=a||c}},Z;
Z=await (async function(){function a(b){var e=Z=b.exports;b={};for(let [g,h]of Object.entries(e))"function"==typeof h?(e=ra(h),b[g]=e):b[g]=h;b=Z=b;va=d._malloc=b.w;d._QTS_Throw=b.x;d._QTS_NewError=b.y;d._QTS_RuntimeSetMemoryLimit=b.z;d._QTS_RuntimeComputeMemoryUsage=b.A;d._QTS_RuntimeDumpMemoryUsage=b.B;d._QTS_RecoverableLeakCheck=b.C;d._QTS_BuildIsSanitizeLeak=b.D;d._QTS_RuntimeSetMaxStackSize=b.E;d._QTS_GetUndefined=b.F;d._QTS_GetNull=b.G;d._QTS_GetFalse=b.H;d._QTS_GetTrue=b.I;d._QTS_NewHostRef=
b.J;d._QTS_GetHostRefId=b.K;d._QTS_NewRuntime=b.L;d._QTS_FreeRuntime=b.M;Aa=d._free=b.N;d._QTS_NewContext=b.O;d._QTS_FreeContext=b.P;d._QTS_FreeValuePointer=b.Q;d._QTS_FreeValuePointerRuntime=b.R;d._QTS_FreeVoidPointer=b.S;d._QTS_FreeCString=b.T;d._QTS_DupValuePointer=b.U;d._QTS_NewObject=b.V;d._QTS_NewObjectProto=b.W;d._QTS_NewArray=b.X;d._QTS_NewArrayBuffer=b.Y;d._QTS_NewFloat64=b.Z;d._QTS_GetFloat64=b._;d._QTS_NewString=b.$;d._QTS_GetString=b.aa;d._QTS_GetArrayBuffer=b.ba;d._QTS_GetArrayBufferLength=
b.ca;d._QTS_NewSymbol=b.da;d._QTS_GetSymbolDescriptionOrKey=b.ea;d._QTS_IsGlobalSymbol=b.fa;d._QTS_IsJobPending=b.ga;d._QTS_ExecutePendingJob=b.ha;d._QTS_GetProp=b.ia;d._QTS_GetPropNumber=b.ja;d._QTS_SetProp=b.ka;d._QTS_DefineProp=b.la;d._QTS_GetOwnPropertyNames=b.ma;d._QTS_Call=b.na;d._QTS_ResolveException=b.oa;d._QTS_Dump=b.pa;d._QTS_Eval=b.qa;d._QTS_GetModuleNamespace=b.ra;d._QTS_Typeof=b.sa;d._QTS_GetLength=b.ta;d._QTS_IsEqual=b.ua;d._QTS_GetGlobalObject=b.va;d._QTS_NewPromiseCapability=b.wa;
d._QTS_PromiseState=b.xa;d._QTS_PromiseResult=b.ya;d._QTS_TestStringArg=b.za;d._QTS_GetDebugLogEnabled=b.Aa;d._QTS_SetDebugLogEnabled=b.Ba;d._QTS_BuildIsDebug=b.Ca;d._QTS_BuildIsAsyncify=b.Da;d._QTS_NewFunction=b.Ea;d._QTS_ArgvGetJSValueConstPointer=b.Fa;d._QTS_RuntimeEnableInterruptHandler=b.Ga;d._QTS_RuntimeDisableInterruptHandler=b.Ha;d._QTS_RuntimeEnableModuleLoader=b.Ia;d._QTS_RuntimeDisableModuleLoader=b.Ja;d._QTS_bjson_encode=b.Ka;d._QTS_bjson_decode=b.La;Ea=b.Ma;Ba=b.Na;Y=b.Oa;Ca=b.Pa;dynCall_iii=
b._a;dynCall_vii=b.bb;dynCall_vi=b.sb;ya=b.tb;sa=b.ub;xa=b.vb;za=b.wb;return Z}var c={a:Fa};if(d.instantiateWasm)return new Promise(b=>{d.instantiateWasm(c,(e,g)=>{b(a(e,g))})});L??=d.locateFile?d.locateFile("emscripten-module.wasm",t):t+"emscripten-module.wasm";return a((await ca(c)).instance)}());
(function(){function a(){d.calledRun=!0;if(!A){I=!0;Z.v();C?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var c=d.postRun.shift();ea.push(c)}da(ea)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ha();da(fa);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();I?moduleRtn=d:moduleRtn=new Promise((a,c)=>{C=a;D=c});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=QuickJSRaw;module.exports.default=QuickJSRaw}else if(typeof define==="function"&&define["amd"])define([],()=>QuickJSRaw);
