async function QuickJSRaw(moduleArg={}){var moduleRtn;var d=moduleArg,aa=!!globalThis.window,n=!!globalThis.WorkerGlobalScope,q=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(q){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}function r(a){a={log:a||function(){}};for(const c of r.Pa)c(a);return d.quickJSEmscriptenExtensions=a}r.Pa=[];d.quickjsEmscriptenInit=r;r.Pa.push(a=>{a.getWasmMemory=function(){return t}});
var u="./this.program",v=(a,c)=>{throw c;},w=import.meta.url,y="",z,A;
if(q){var fs=require("node:fs");w.startsWith("file:")&&(y=require("node:path").dirname(require("node:url").fileURLToPath(w))+"/");A=a=>{a=B(a)?new URL(a):a;return fs.readFileSync(a)};z=async a=>{a=B(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(u=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);v=(a,c)=>{process.exitCode=a;throw c;}}else if(aa||n){try{y=(new URL(".",w)).href}catch{}n&&(A=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";
c.send(null);return new Uint8Array(c.response)});z=async a=>{if(B(a))return new Promise((b,e)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?b(f.response):e(f.status)};f.onerror=e;f.send(null)});var c=await fetch(a,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+" : "+c.url);}}
var C=console.log.bind(console),D=console.error.bind(console),E,F=!1,G,B=a=>a.startsWith("file://"),H,I,J,K,L,M,ba=!1;function ca(){var a=t.buffer;d.HEAP8=J=new Int8Array(a);new Int16Array(a);d.HEAPU8=K=new Uint8Array(a);new Uint16Array(a);L=new Int32Array(a);M=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}
function N(a){d.onAbort?.(a);a="Aborted("+a+")";D(a);F=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");I?.(a);throw a;}var O;async function da(a){if(!E)try{var c=await z(a);return new Uint8Array(c)}catch{}if(a==O&&E)a=new Uint8Array(E);else if(A)a=A(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ea(a,c){try{var b=await da(a);return await WebAssembly.instantiate(b,c)}catch(e){D(`failed to asynchronously prepare wasm: ${e}`),N(e)}}async function fa(a){var c=O;if(!E&&!B(c)&&!q)try{var b=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){D(`wasm streaming compile failed: ${e}`),D("falling back to ArrayBuffer instantiation")}return ea(c,a)}
class P{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ha=a=>{for(;0<a.length;)a.shift()(d)},ia=[],ja=[],ka=()=>{var a=d.preRun.shift();ja.push(a)},Q=!0,t,la=new TextDecoder,ma=(a,c,b,e)=>{b=c+b;if(e)return b;for(;a[c]&&!(c>=b);)++c;return c},R=(a,c,b)=>a?la.decode(K.subarray(a,ma(K,a,c,b))):"",S=0,na=[0,31,60,91,121,152,182,213,244,274,305,335],oa=[0,31,59,90,120,151,181,212,243,273,304,334],T={},pa=a=>{G=a;Q||0<S||(d.onExit?.(a),F=!0);v(a,new P(a))},qa=a=>{if(!F)try{a()}catch(c){c instanceof P||"unwind"==c||v(1,c)}finally{if(!(Q||0<S))try{G=a=G,
pa(a)}catch(c){c instanceof P||"unwind"==c||v(1,c)}}},U=(a,c,b)=>{var e=K;if(!(0<b))return 0;var f=c;b=c+b-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=b)break;e[c++]=h}else if(2047>=h){if(c+1>=b)break;e[c++]=192|h>>6;e[c++]=128|h&63}else if(65535>=h){if(c+2>=b)break;e[c++]=224|h>>12;e[c++]=128|h>>6&63;e[c++]=128|h&63}else{if(c+3>=b)break;e[c++]=240|h>>18;e[c++]=128|h>>12&63;e[c++]=128|h>>6&63;e[c++]=128|h&63;g++}}e[c]=0;return c-f},V={},ra=()=>{if(!W){var a={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:u||"./this.program"},c;for(c in V)void 0===V[c]?delete a[c]:a[c]=V[c];var b=[];for(c in a)b.push(`${c}=${a[c]}`);W=b}return W},W,X=a=>{for(var c=0,b=0;b<a.length;++b){var e=a.charCodeAt(b);127>=e?c++:2047>=e?c+=2:55296<=e&&57343>=e?(c+=4,++b):c+=3}return c},sa=[null,[],[]],va=(a,c,b,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=X(k)+1;var p=Y(l);U(k,p,
l);l=p}return l},array:k=>{var l=Y(k.length);J.set(k,l);return l}};a=d["_"+a];var g=[],h=0;if(e)for(var m=0;m<e.length;m++){var x=f[b[m]];x?(0===h&&(h=ta()),g[m]=x(e[m])):g[m]=e[m]}b=a(...g);return b=function(k){0!==h&&ua(h);return"string"===c?R(k):"boolean"===c?!!k:k}(b)};d.wasmMemory?t=d.wasmMemory:t=new WebAssembly.Memory({initial:(d.INITIAL_MEMORY||16777216)/65536,maximum:32768});ca();d.noExitRuntime&&(Q=d.noExitRuntime);d.print&&(C=d.print);d.printErr&&(D=d.printErr);d.wasmBinary&&(E=d.wasmBinary);
d.thisProgram&&(u=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.cwrap=(a,c,b,e)=>{var f=!b||b.every(g=>"number"===g||"boolean"===g);return"string"!==c&&f&&!e?d["_"+a]:(...g)=>va(a,c,b,g)};d.UTF8ToString=R;d.stringToUTF8=(a,c,b)=>U(a,c,b);d.lengthBytesUTF8=X;
var wa,ua,Y,ta,xa={b:(a,c,b,e)=>N(`Assertion failed: ${R(a)}, at: `+[c?R(c):"unknown filename",b,e?R(e):"unknown function"]),q:()=>N(""),l:()=>{Q=!1;S=0},m:function(a,c){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);L[c>>2]=a.getSeconds();L[c+4>>2]=a.getMinutes();L[c+8>>2]=a.getHours();L[c+12>>2]=a.getDate();L[c+16>>2]=a.getMonth();L[c+20>>2]=a.getFullYear()-1900;L[c+24>>2]=a.getDay();var b=a.getFullYear();L[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?oa:na)[a.getMonth()]+
a.getDate()-1|0;L[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();L[c+32>>2]=(b!=e&&a.getTimezoneOffset()==Math.min(e,b))|0},j:(a,c)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!c)return 0;var b=setTimeout(()=>{delete T[a];qa(()=>wa(a,performance.now()))},c);T[a]={id:b,Qa:c};return 0},n:(a,c,b,e)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();
M[a>>2]=60*Math.max(g,f);L[c>>2]=Number(g!=f);c=h=>{var m=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=c(g);c=c(f);f<g?(U(a,b,17),U(c,e,17)):(U(a,e,17),U(c,b,17))},p:()=>Date.now(),k:a=>{var c=K.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=c*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-t.buffer.byteLength+65535)/65536|0;try{t.grow(e);ca();var f=1;break a}catch(g){}f=
void 0}if(f)return!0}return!1},e:(a,c)=>{var b=0,e=0,f;for(f of ra()){var g=c+b;M[a+e>>2]=g;b+=U(f,g,Infinity)+1;e+=4}return 0},f:(a,c)=>{var b=ra();M[a>>2]=b.length;a=0;for(var e of b)a+=X(e)+1;M[c>>2]=a;return 0},d:()=>52,o:function(){return 70},c:(a,c,b,e)=>{for(var f=0,g=0;g<b;g++){var h=M[c>>2],m=M[c+4>>2];c+=8;for(var x=0;x<m;x++){var k=a,l=K[h+x],p=sa[k];0===l||10===l?(k=1===k?C:D,l=ma(p,0),l=la.decode(p.buffer?p.subarray(0,l):new Uint8Array(p.slice(0,l))),k(l),p.length=0):p.push(l)}f+=m}M[e>>
2]=f;return 0},a:t,r:pa,s:function(a,c,b,e,f){return d.callbacks.callFunction(void 0,a,c,b,e,f)},i:function(a){return d.callbacks.shouldInterrupt(void 0,a)},h:function(a,c,b){b=R(b);return d.callbacks.loadModuleSource(void 0,a,c,b)},g:function(a,c,b,e){b=R(b);e=R(e);return d.callbacks.normalizeModule(void 0,a,c,b,e)},t:function(a,c){d.callbacks.freeHostRef(void 0,a,c)}},Z;
Z=await (async function(){function a(b){b=Z=b.exports;d._malloc=b.v;d._QTS_Throw=b.w;d._QTS_NewError=b.x;d._QTS_RuntimeSetMemoryLimit=b.y;d._QTS_RuntimeComputeMemoryUsage=b.z;d._QTS_RuntimeDumpMemoryUsage=b.A;d._QTS_RecoverableLeakCheck=b.B;d._QTS_BuildIsSanitizeLeak=b.C;d._QTS_RuntimeSetMaxStackSize=b.D;d._QTS_GetUndefined=b.E;d._QTS_GetNull=b.F;d._QTS_GetFalse=b.G;d._QTS_GetTrue=b.H;d._QTS_NewHostRef=b.I;d._QTS_GetHostRefId=b.J;d._QTS_NewRuntime=b.K;d._QTS_FreeRuntime=b.L;d._free=b.M;
d._QTS_NewContext=b.N;d._QTS_FreeContext=b.O;d._QTS_FreeValuePointer=b.P;d._QTS_FreeValuePointerRuntime=b.Q;d._QTS_FreeVoidPointer=b.R;d._QTS_FreeCString=b.S;d._QTS_DupValuePointer=b.T;d._QTS_NewObject=b.U;d._QTS_NewObjectProto=b.V;d._QTS_NewArray=b.W;d._QTS_NewArrayBuffer=b.X;d._QTS_NewFloat64=b.Y;d._QTS_GetFloat64=b.Z;d._QTS_NewString=b._;d._QTS_GetString=b.$;d._QTS_GetArrayBuffer=b.aa;d._QTS_GetArrayBufferLength=b.ba;d._QTS_NewSymbol=b.ca;d._QTS_GetSymbolDescriptionOrKey=b.da;d._QTS_IsGlobalSymbol=
b.ea;d._QTS_IsJobPending=b.fa;d._QTS_ExecutePendingJob=b.ga;d._QTS_GetProp=b.ha;d._QTS_GetPropNumber=b.ia;d._QTS_SetProp=b.ja;d._QTS_DefineProp=b.ka;d._QTS_GetOwnPropertyNames=b.la;d._QTS_Call=b.ma;d._QTS_ResolveException=b.na;d._QTS_Dump=b.oa;d._QTS_Eval=b.pa;d._QTS_GetModuleNamespace=b.qa;d._QTS_Typeof=b.ra;d._QTS_GetLength=b.sa;d._QTS_IsEqual=b.ta;d._QTS_GetGlobalObject=b.ua;d._QTS_NewPromiseCapability=b.va;d._QTS_PromiseState=b.wa;d._QTS_PromiseResult=b.xa;d._QTS_TestStringArg=b.ya;d._QTS_GetDebugLogEnabled=
b.za;d._QTS_SetDebugLogEnabled=b.Aa;d._QTS_BuildIsDebug=b.Ba;d._QTS_BuildIsAsyncify=b.Ca;d._QTS_NewFunction=b.Da;d._QTS_ArgvGetJSValueConstPointer=b.Ea;d._QTS_RuntimeEnableInterruptHandler=b.Fa;d._QTS_RuntimeDisableInterruptHandler=b.Ga;d._QTS_RuntimeEnableModuleLoader=b.Ha;d._QTS_RuntimeDisableModuleLoader=b.Ia;d._QTS_bjson_encode=b.Ja;d._QTS_bjson_decode=b.Ka;wa=b.La;ua=b.Ma;Y=b.Na;ta=b.Oa;return Z}var c={a:xa};if(d.instantiateWasm)return new Promise(b=>{d.instantiateWasm(c,(e,f)=>{b(a(e,f))})});
O??=d.locateFile?d.locateFile?d.locateFile("emscripten-module.wasm",y):y+"emscripten-module.wasm":(new URL("emscripten-module.wasm",import.meta.url)).href;return a((await fa(c)).instance)}());
(function(){function a(){d.calledRun=!0;if(!F){ba=!0;Z.u();H?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var c=d.postRun.shift();ia.push(c)}ha(ia)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ka();ha(ja);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();ba?moduleRtn=d:moduleRtn=new Promise((a,c)=>{H=a;I=c});
;return moduleRtn}export default QuickJSRaw;
