/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileStatus } from './file-status';
/**
 *
 * @export
 * @interface GitStatus
 */
export interface GitStatus {
    /**
     *
     * @type {number}
     * @memberof GitStatus
     */
    'ahead'?: number;
    /**
     *
     * @type {number}
     * @memberof GitStatus
     */
    'behind'?: number;
    /**
     *
     * @type {boolean}
     * @memberof GitStatus
     */
    'branchPublished'?: boolean;
    /**
     *
     * @type {string}
     * @memberof GitStatus
     */
    'currentBranch': string;
    /**
     *
     * @type {Array<FileStatus>}
     * @memberof GitStatus
     */
    'fileStatus': Array<FileStatus>;
}
