/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { CreateSandbox } from '../models';
import type { MetricsResponse } from '../models';
import type { PaginatedLogs } from '../models';
import type { PaginatedSandboxes } from '../models';
import type { PaginatedTraces } from '../models';
import type { PortPreviewUrl } from '../models';
import type { ResizeSandbox } from '../models';
import type { Sandbox } from '../models';
import type { SandboxLabels } from '../models';
import type { SignedPortPreviewUrl } from '../models';
import type { SshAccessDto } from '../models';
import type { SshAccessValidationDto } from '../models';
import type { ToolboxProxyUrl } from '../models';
import type { TraceSpan } from '../models';
import type { UpdateSandboxStateDto } from '../models';
import type { Url } from '../models';
/**
 * SandboxApi - axios parameter creator
 * @export
 */
export declare const SandboxApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Archive sandbox
     * @param {string} sandboxIdOrName
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    archiveSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create sandbox backup
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBackup: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create a new sandbox
     * @param {CreateSandbox} createSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSandbox: (createSandbox: CreateSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInMinutes] Expiration time in minutes (default: 60)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSshAccess: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, expiresInMinutes?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Expire signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to expire signed preview URL for
     * @param {string} token Token to expire signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    expireSignedPortPreviewUrl: (sandboxIdOrName: string, port: number, token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * This endpoint is deprecated. Use `getBuildLogsUrl` instead.
     * @summary Get build logs
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    getBuildLogs: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get build logs URL
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBuildLogsUrl: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortPreviewUrl: (sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get sandbox details
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, verbose?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Retrieve OTEL logs for a sandbox within a time range
     * @summary Get sandbox logs
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
     * @param {string} [search] Search in log body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxLogs: (sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, severities?: Array<string>, search?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Retrieve OTEL metrics for a sandbox within a time range
     * @summary Get sandbox metrics
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {Array<string>} [metricNames] Filter by metric names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxMetrics: (sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Retrieve all spans for a specific trace
     * @summary Get trace spans
     * @param {string} sandboxId ID of the sandbox
     * @param {string} traceId ID of the trace
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraceSpans: (sandboxId: string, traceId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Retrieve OTEL traces for a sandbox within a time range
     * @summary Get sandbox traces
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraces: (sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get sandboxes for the authenticated runner
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [states] Comma-separated list of sandbox states to filter by
     * @param {boolean} [skipReconcilingSandboxes] Skip sandboxes where state differs from desired state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxesForRunner: (xDaytonaOrganizationID?: string, states?: string, skipReconcilingSandboxes?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInSeconds] Expiration time in seconds (default: 60 seconds)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSignedPortPreviewUrl: (sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, expiresInSeconds?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get toolbox proxy URL for a sandbox
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getToolboxProxyUrl: (sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List all sandboxes
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include errored and deleted sandboxes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxes: (xDaytonaOrganizationID?: string, verbose?: boolean, labels?: string, includeErroredDeleted?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List all sandboxes paginated
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [id] Filter by partial ID match
     * @param {string} [name] Filter by partial name match
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include results with errored state and deleted desired state
     * @param {Array<ListSandboxesPaginatedStatesEnum>} [states] List of states to filter by
     * @param {Array<string>} [snapshots] List of snapshot names to filter by
     * @param {Array<string>} [regions] List of regions to filter by
     * @param {number} [minCpu] Minimum CPU
     * @param {number} [maxCpu] Maximum CPU
     * @param {number} [minMemoryGiB] Minimum memory in GiB
     * @param {number} [maxMemoryGiB] Maximum memory in GiB
     * @param {number} [minDiskGiB] Minimum disk space in GiB
     * @param {number} [maxDiskGiB] Maximum disk space in GiB
     * @param {Date} [lastEventAfter] Include items with last event after this timestamp
     * @param {Date} [lastEventBefore] Include items with last event before this timestamp
     * @param {ListSandboxesPaginatedSortEnum} [sort] Field to sort by
     * @param {ListSandboxesPaginatedOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxesPaginated: (xDaytonaOrganizationID?: string, page?: number, limit?: number, id?: string, name?: string, labels?: string, includeErroredDeleted?: boolean, states?: Array<ListSandboxesPaginatedStatesEnum>, snapshots?: Array<string>, regions?: Array<string>, minCpu?: number, maxCpu?: number, minMemoryGiB?: number, maxMemoryGiB?: number, minDiskGiB?: number, maxDiskGiB?: number, lastEventAfter?: Date, lastEventBefore?: Date, sort?: ListSandboxesPaginatedSortEnum, order?: ListSandboxesPaginatedOrderEnum, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Recover sandbox from error state
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recoverSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Replace sandbox labels
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {SandboxLabels} sandboxLabels
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceLabels: (sandboxIdOrName: string, sandboxLabels: SandboxLabels, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Resize sandbox resources
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {ResizeSandbox} resizeSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resizeSandbox: (sandboxIdOrName: string, resizeSandbox: ResizeSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Revoke SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [token] SSH access token to revoke. If not provided, all SSH access for the sandbox will be revoked.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeSshAccess: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, token?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Set sandbox auto-archive interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-archive interval in minutes (0 means the maximum interval will be used)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoArchiveInterval: (sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Set sandbox auto-delete interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoDeleteInterval: (sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Set sandbox auto-stop interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-stop interval in minutes (0 to disable)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutostopInterval: (sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Start sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Stop sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    stopSandbox: (sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update sandbox last activity
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateLastActivity: (sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update public status
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {boolean} isPublic Public status to set
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePublicStatus: (sandboxIdOrName: string, isPublic: boolean, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update sandbox state
     * @param {string} sandboxId ID of the sandbox
     * @param {UpdateSandboxStateDto} updateSandboxStateDto
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSandboxState: (sandboxId: string, updateSandboxStateDto: UpdateSandboxStateDto, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Validate SSH access for sandbox
     * @param {string} token SSH access token to validate
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateSshAccess: (token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * SandboxApi - functional programming interface
 * @export
 */
export declare const SandboxApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Archive sandbox
     * @param {string} sandboxIdOrName
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    archiveSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Create sandbox backup
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBackup(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Create a new sandbox
     * @param {CreateSandbox} createSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSandbox(createSandbox: CreateSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Create SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInMinutes] Expiration time in minutes (default: 60)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, expiresInMinutes?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SshAccessDto>>;
    /**
     *
     * @summary Delete sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Expire signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to expire signed preview URL for
     * @param {string} token Token to expire signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    expireSignedPortPreviewUrl(sandboxIdOrName: string, port: number, token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * This endpoint is deprecated. Use `getBuildLogsUrl` instead.
     * @summary Get build logs
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    getBuildLogs(sandboxIdOrName: string, xDaytonaOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get build logs URL
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBuildLogsUrl(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Url>>;
    /**
     *
     * @summary Get preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PortPreviewUrl>>;
    /**
     *
     * @summary Get sandbox details
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, verbose?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     * Retrieve OTEL logs for a sandbox within a time range
     * @summary Get sandbox logs
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
     * @param {string} [search] Search in log body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxLogs(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, severities?: Array<string>, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedLogs>>;
    /**
     * Retrieve OTEL metrics for a sandbox within a time range
     * @summary Get sandbox metrics
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {Array<string>} [metricNames] Filter by metric names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxMetrics(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MetricsResponse>>;
    /**
     * Retrieve all spans for a specific trace
     * @summary Get trace spans
     * @param {string} sandboxId ID of the sandbox
     * @param {string} traceId ID of the trace
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraceSpans(sandboxId: string, traceId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TraceSpan>>>;
    /**
     * Retrieve OTEL traces for a sandbox within a time range
     * @summary Get sandbox traces
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraces(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedTraces>>;
    /**
     *
     * @summary Get sandboxes for the authenticated runner
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [states] Comma-separated list of sandbox states to filter by
     * @param {boolean} [skipReconcilingSandboxes] Skip sandboxes where state differs from desired state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxesForRunner(xDaytonaOrganizationID?: string, states?: string, skipReconcilingSandboxes?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Sandbox>>>;
    /**
     *
     * @summary Get signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInSeconds] Expiration time in seconds (default: 60 seconds)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSignedPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, expiresInSeconds?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignedPortPreviewUrl>>;
    /**
     *
     * @summary Get toolbox proxy URL for a sandbox
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getToolboxProxyUrl(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToolboxProxyUrl>>;
    /**
     *
     * @summary List all sandboxes
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include errored and deleted sandboxes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxes(xDaytonaOrganizationID?: string, verbose?: boolean, labels?: string, includeErroredDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Sandbox>>>;
    /**
     *
     * @summary List all sandboxes paginated
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [id] Filter by partial ID match
     * @param {string} [name] Filter by partial name match
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include results with errored state and deleted desired state
     * @param {Array<ListSandboxesPaginatedStatesEnum>} [states] List of states to filter by
     * @param {Array<string>} [snapshots] List of snapshot names to filter by
     * @param {Array<string>} [regions] List of regions to filter by
     * @param {number} [minCpu] Minimum CPU
     * @param {number} [maxCpu] Maximum CPU
     * @param {number} [minMemoryGiB] Minimum memory in GiB
     * @param {number} [maxMemoryGiB] Maximum memory in GiB
     * @param {number} [minDiskGiB] Minimum disk space in GiB
     * @param {number} [maxDiskGiB] Maximum disk space in GiB
     * @param {Date} [lastEventAfter] Include items with last event after this timestamp
     * @param {Date} [lastEventBefore] Include items with last event before this timestamp
     * @param {ListSandboxesPaginatedSortEnum} [sort] Field to sort by
     * @param {ListSandboxesPaginatedOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxesPaginated(xDaytonaOrganizationID?: string, page?: number, limit?: number, id?: string, name?: string, labels?: string, includeErroredDeleted?: boolean, states?: Array<ListSandboxesPaginatedStatesEnum>, snapshots?: Array<string>, regions?: Array<string>, minCpu?: number, maxCpu?: number, minMemoryGiB?: number, maxMemoryGiB?: number, minDiskGiB?: number, maxDiskGiB?: number, lastEventAfter?: Date, lastEventBefore?: Date, sort?: ListSandboxesPaginatedSortEnum, order?: ListSandboxesPaginatedOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSandboxes>>;
    /**
     *
     * @summary Recover sandbox from error state
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recoverSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Replace sandbox labels
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {SandboxLabels} sandboxLabels
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceLabels(sandboxIdOrName: string, sandboxLabels: SandboxLabels, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SandboxLabels>>;
    /**
     *
     * @summary Resize sandbox resources
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {ResizeSandbox} resizeSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resizeSandbox(sandboxIdOrName: string, resizeSandbox: ResizeSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Revoke SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [token] SSH access token to revoke. If not provided, all SSH access for the sandbox will be revoked.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, token?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Set sandbox auto-archive interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-archive interval in minutes (0 means the maximum interval will be used)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoArchiveInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Set sandbox auto-delete interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoDeleteInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Set sandbox auto-stop interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-stop interval in minutes (0 to disable)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutostopInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Start sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Stop sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    stopSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Update sandbox last activity
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateLastActivity(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Update public status
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {boolean} isPublic Public status to set
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePublicStatus(sandboxIdOrName: string, isPublic: boolean, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Sandbox>>;
    /**
     *
     * @summary Update sandbox state
     * @param {string} sandboxId ID of the sandbox
     * @param {UpdateSandboxStateDto} updateSandboxStateDto
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSandboxState(sandboxId: string, updateSandboxStateDto: UpdateSandboxStateDto, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Validate SSH access for sandbox
     * @param {string} token SSH access token to validate
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateSshAccess(token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SshAccessValidationDto>>;
};
/**
 * SandboxApi - factory interface
 * @export
 */
export declare const SandboxApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Archive sandbox
     * @param {string} sandboxIdOrName
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    archiveSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Create sandbox backup
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBackup(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Create a new sandbox
     * @param {CreateSandbox} createSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSandbox(createSandbox: CreateSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Create SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInMinutes] Expiration time in minutes (default: 60)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, expiresInMinutes?: number, options?: RawAxiosRequestConfig): AxiosPromise<SshAccessDto>;
    /**
     *
     * @summary Delete sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Expire signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to expire signed preview URL for
     * @param {string} token Token to expire signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    expireSignedPortPreviewUrl(sandboxIdOrName: string, port: number, token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     * This endpoint is deprecated. Use `getBuildLogsUrl` instead.
     * @summary Get build logs
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    getBuildLogs(sandboxIdOrName: string, xDaytonaOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get build logs URL
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBuildLogsUrl(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Url>;
    /**
     *
     * @summary Get preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<PortPreviewUrl>;
    /**
     *
     * @summary Get sandbox details
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, verbose?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     * Retrieve OTEL logs for a sandbox within a time range
     * @summary Get sandbox logs
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
     * @param {string} [search] Search in log body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxLogs(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, severities?: Array<string>, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedLogs>;
    /**
     * Retrieve OTEL metrics for a sandbox within a time range
     * @summary Get sandbox metrics
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {Array<string>} [metricNames] Filter by metric names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxMetrics(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<MetricsResponse>;
    /**
     * Retrieve all spans for a specific trace
     * @summary Get trace spans
     * @param {string} sandboxId ID of the sandbox
     * @param {string} traceId ID of the trace
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraceSpans(sandboxId: string, traceId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<TraceSpan>>;
    /**
     * Retrieve OTEL traces for a sandbox within a time range
     * @summary Get sandbox traces
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxTraces(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedTraces>;
    /**
     *
     * @summary Get sandboxes for the authenticated runner
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [states] Comma-separated list of sandbox states to filter by
     * @param {boolean} [skipReconcilingSandboxes] Skip sandboxes where state differs from desired state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSandboxesForRunner(xDaytonaOrganizationID?: string, states?: string, skipReconcilingSandboxes?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<Sandbox>>;
    /**
     *
     * @summary Get signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInSeconds] Expiration time in seconds (default: 60 seconds)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSignedPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, expiresInSeconds?: number, options?: RawAxiosRequestConfig): AxiosPromise<SignedPortPreviewUrl>;
    /**
     *
     * @summary Get toolbox proxy URL for a sandbox
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getToolboxProxyUrl(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<ToolboxProxyUrl>;
    /**
     *
     * @summary List all sandboxes
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include errored and deleted sandboxes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxes(xDaytonaOrganizationID?: string, verbose?: boolean, labels?: string, includeErroredDeleted?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<Sandbox>>;
    /**
     *
     * @summary List all sandboxes paginated
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [id] Filter by partial ID match
     * @param {string} [name] Filter by partial name match
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include results with errored state and deleted desired state
     * @param {Array<ListSandboxesPaginatedStatesEnum>} [states] List of states to filter by
     * @param {Array<string>} [snapshots] List of snapshot names to filter by
     * @param {Array<string>} [regions] List of regions to filter by
     * @param {number} [minCpu] Minimum CPU
     * @param {number} [maxCpu] Maximum CPU
     * @param {number} [minMemoryGiB] Minimum memory in GiB
     * @param {number} [maxMemoryGiB] Maximum memory in GiB
     * @param {number} [minDiskGiB] Minimum disk space in GiB
     * @param {number} [maxDiskGiB] Maximum disk space in GiB
     * @param {Date} [lastEventAfter] Include items with last event after this timestamp
     * @param {Date} [lastEventBefore] Include items with last event before this timestamp
     * @param {ListSandboxesPaginatedSortEnum} [sort] Field to sort by
     * @param {ListSandboxesPaginatedOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSandboxesPaginated(xDaytonaOrganizationID?: string, page?: number, limit?: number, id?: string, name?: string, labels?: string, includeErroredDeleted?: boolean, states?: Array<ListSandboxesPaginatedStatesEnum>, snapshots?: Array<string>, regions?: Array<string>, minCpu?: number, maxCpu?: number, minMemoryGiB?: number, maxMemoryGiB?: number, minDiskGiB?: number, maxDiskGiB?: number, lastEventAfter?: Date, lastEventBefore?: Date, sort?: ListSandboxesPaginatedSortEnum, order?: ListSandboxesPaginatedOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedSandboxes>;
    /**
     *
     * @summary Recover sandbox from error state
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recoverSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Replace sandbox labels
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {SandboxLabels} sandboxLabels
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceLabels(sandboxIdOrName: string, sandboxLabels: SandboxLabels, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SandboxLabels>;
    /**
     *
     * @summary Resize sandbox resources
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {ResizeSandbox} resizeSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resizeSandbox(sandboxIdOrName: string, resizeSandbox: ResizeSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Revoke SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [token] SSH access token to revoke. If not provided, all SSH access for the sandbox will be revoked.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, token?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Set sandbox auto-archive interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-archive interval in minutes (0 means the maximum interval will be used)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoArchiveInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Set sandbox auto-delete interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutoDeleteInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Set sandbox auto-stop interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-stop interval in minutes (0 to disable)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setAutostopInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Start sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Stop sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    stopSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Update sandbox last activity
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateLastActivity(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Update public status
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {boolean} isPublic Public status to set
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePublicStatus(sandboxIdOrName: string, isPublic: boolean, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Sandbox>;
    /**
     *
     * @summary Update sandbox state
     * @param {string} sandboxId ID of the sandbox
     * @param {UpdateSandboxStateDto} updateSandboxStateDto
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSandboxState(sandboxId: string, updateSandboxStateDto: UpdateSandboxStateDto, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Validate SSH access for sandbox
     * @param {string} token SSH access token to validate
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateSshAccess(token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SshAccessValidationDto>;
};
/**
 * SandboxApi - object-oriented interface
 * @export
 * @class SandboxApi
 * @extends {BaseAPI}
 */
export declare class SandboxApi extends BaseAPI {
    /**
     *
     * @summary Archive sandbox
     * @param {string} sandboxIdOrName
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    archiveSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Create sandbox backup
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    createBackup(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Create a new sandbox
     * @param {CreateSandbox} createSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    createSandbox(createSandbox: CreateSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Create SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInMinutes] Expiration time in minutes (default: 60)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    createSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, expiresInMinutes?: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SshAccessDto, any, {}>>;
    /**
     *
     * @summary Delete sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    deleteSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Expire signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to expire signed preview URL for
     * @param {string} token Token to expire signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    expireSignedPortPreviewUrl(sandboxIdOrName: string, port: number, token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     * This endpoint is deprecated. Use `getBuildLogsUrl` instead.
     * @summary Get build logs
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getBuildLogs(sandboxIdOrName: string, xDaytonaOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get build logs URL
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getBuildLogsUrl(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Url, any, {}>>;
    /**
     *
     * @summary Get preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PortPreviewUrl, any, {}>>;
    /**
     *
     * @summary Get sandbox details
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, verbose?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     * Retrieve OTEL logs for a sandbox within a time range
     * @summary Get sandbox logs
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
     * @param {string} [search] Search in log body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandboxLogs(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, severities?: Array<string>, search?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PaginatedLogs, any, {}>>;
    /**
     * Retrieve OTEL metrics for a sandbox within a time range
     * @summary Get sandbox metrics
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {Array<string>} [metricNames] Filter by metric names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandboxMetrics(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<MetricsResponse, any, {}>>;
    /**
     * Retrieve all spans for a specific trace
     * @summary Get trace spans
     * @param {string} sandboxId ID of the sandbox
     * @param {string} traceId ID of the trace
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandboxTraceSpans(sandboxId: string, traceId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<TraceSpan[], any, {}>>;
    /**
     * Retrieve OTEL traces for a sandbox within a time range
     * @summary Get sandbox traces
     * @param {string} sandboxId ID of the sandbox
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandboxTraces(sandboxId: string, from: Date, to: Date, xDaytonaOrganizationID?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PaginatedTraces, any, {}>>;
    /**
     *
     * @summary Get sandboxes for the authenticated runner
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [states] Comma-separated list of sandbox states to filter by
     * @param {boolean} [skipReconcilingSandboxes] Skip sandboxes where state differs from desired state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSandboxesForRunner(xDaytonaOrganizationID?: string, states?: string, skipReconcilingSandboxes?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox[], any, {}>>;
    /**
     *
     * @summary Get signed preview URL for a sandbox port
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} port Port number to get signed preview URL for
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [expiresInSeconds] Expiration time in seconds (default: 60 seconds)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getSignedPortPreviewUrl(sandboxIdOrName: string, port: number, xDaytonaOrganizationID?: string, expiresInSeconds?: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SignedPortPreviewUrl, any, {}>>;
    /**
     *
     * @summary Get toolbox proxy URL for a sandbox
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    getToolboxProxyUrl(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ToolboxProxyUrl, any, {}>>;
    /**
     *
     * @summary List all sandboxes
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [verbose] Include verbose output
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include errored and deleted sandboxes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    listSandboxes(xDaytonaOrganizationID?: string, verbose?: boolean, labels?: string, includeErroredDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox[], any, {}>>;
    /**
     *
     * @summary List all sandboxes paginated
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [id] Filter by partial ID match
     * @param {string} [name] Filter by partial name match
     * @param {string} [labels] JSON encoded labels to filter by
     * @param {boolean} [includeErroredDeleted] Include results with errored state and deleted desired state
     * @param {Array<ListSandboxesPaginatedStatesEnum>} [states] List of states to filter by
     * @param {Array<string>} [snapshots] List of snapshot names to filter by
     * @param {Array<string>} [regions] List of regions to filter by
     * @param {number} [minCpu] Minimum CPU
     * @param {number} [maxCpu] Maximum CPU
     * @param {number} [minMemoryGiB] Minimum memory in GiB
     * @param {number} [maxMemoryGiB] Maximum memory in GiB
     * @param {number} [minDiskGiB] Minimum disk space in GiB
     * @param {number} [maxDiskGiB] Maximum disk space in GiB
     * @param {Date} [lastEventAfter] Include items with last event after this timestamp
     * @param {Date} [lastEventBefore] Include items with last event before this timestamp
     * @param {ListSandboxesPaginatedSortEnum} [sort] Field to sort by
     * @param {ListSandboxesPaginatedOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    listSandboxesPaginated(xDaytonaOrganizationID?: string, page?: number, limit?: number, id?: string, name?: string, labels?: string, includeErroredDeleted?: boolean, states?: Array<ListSandboxesPaginatedStatesEnum>, snapshots?: Array<string>, regions?: Array<string>, minCpu?: number, maxCpu?: number, minMemoryGiB?: number, maxMemoryGiB?: number, minDiskGiB?: number, maxDiskGiB?: number, lastEventAfter?: Date, lastEventBefore?: Date, sort?: ListSandboxesPaginatedSortEnum, order?: ListSandboxesPaginatedOrderEnum, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PaginatedSandboxes, any, {}>>;
    /**
     *
     * @summary Recover sandbox from error state
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    recoverSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Replace sandbox labels
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {SandboxLabels} sandboxLabels
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    replaceLabels(sandboxIdOrName: string, sandboxLabels: SandboxLabels, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SandboxLabels, any, {}>>;
    /**
     *
     * @summary Resize sandbox resources
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {ResizeSandbox} resizeSandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    resizeSandbox(sandboxIdOrName: string, resizeSandbox: ResizeSandbox, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Revoke SSH access for sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [token] SSH access token to revoke. If not provided, all SSH access for the sandbox will be revoked.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    revokeSshAccess(sandboxIdOrName: string, xDaytonaOrganizationID?: string, token?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Set sandbox auto-archive interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-archive interval in minutes (0 means the maximum interval will be used)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    setAutoArchiveInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Set sandbox auto-delete interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    setAutoDeleteInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Set sandbox auto-stop interval
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {number} interval Auto-stop interval in minutes (0 to disable)
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    setAutostopInterval(sandboxIdOrName: string, interval: number, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Start sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    startSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Stop sandbox
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    stopSandbox(sandboxIdOrName: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Update sandbox last activity
     * @param {string} sandboxId ID of the sandbox
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    updateLastActivity(sandboxId: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Update public status
     * @param {string} sandboxIdOrName ID or name of the sandbox
     * @param {boolean} isPublic Public status to set
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    updatePublicStatus(sandboxIdOrName: string, isPublic: boolean, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Sandbox, any, {}>>;
    /**
     *
     * @summary Update sandbox state
     * @param {string} sandboxId ID of the sandbox
     * @param {UpdateSandboxStateDto} updateSandboxStateDto
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    updateSandboxState(sandboxId: string, updateSandboxStateDto: UpdateSandboxStateDto, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Validate SSH access for sandbox
     * @param {string} token SSH access token to validate
     * @param {string} [xDaytonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxApi
     */
    validateSshAccess(token: string, xDaytonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SshAccessValidationDto, any, {}>>;
}
/**
 * @export
 */
export declare const ListSandboxesPaginatedStatesEnum: {
    readonly CREATING: "creating";
    readonly RESTORING: "restoring";
    readonly DESTROYING: "destroying";
    readonly STARTED: "started";
    readonly STOPPED: "stopped";
    readonly STARTING: "starting";
    readonly STOPPING: "stopping";
    readonly ERROR: "error";
    readonly BUILD_FAILED: "build_failed";
    readonly PENDING_BUILD: "pending_build";
    readonly BUILDING_SNAPSHOT: "building_snapshot";
    readonly UNKNOWN: "unknown";
    readonly PULLING_SNAPSHOT: "pulling_snapshot";
    readonly ARCHIVED: "archived";
    readonly ARCHIVING: "archiving";
    readonly RESIZING: "resizing";
};
export type ListSandboxesPaginatedStatesEnum = typeof ListSandboxesPaginatedStatesEnum[keyof typeof ListSandboxesPaginatedStatesEnum];
/**
 * @export
 */
export declare const ListSandboxesPaginatedSortEnum: {
    readonly ID: "id";
    readonly NAME: "name";
    readonly STATE: "state";
    readonly SNAPSHOT: "snapshot";
    readonly REGION: "region";
    readonly UPDATED_AT: "updatedAt";
    readonly CREATED_AT: "createdAt";
};
export type ListSandboxesPaginatedSortEnum = typeof ListSandboxesPaginatedSortEnum[keyof typeof ListSandboxesPaginatedSortEnum];
/**
 * @export
 */
export declare const ListSandboxesPaginatedOrderEnum: {
    readonly ASC: "asc";
    readonly DESC: "desc";
};
export type ListSandboxesPaginatedOrderEnum = typeof ListSandboxesPaginatedOrderEnum[keyof typeof ListSandboxesPaginatedOrderEnum];
