/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CompletionItem } from './completion-item';
/**
 *
 * @export
 * @interface CompletionList
 */
export interface CompletionList {
    /**
     *
     * @type {boolean}
     * @memberof CompletionList
     */
    'isIncomplete': boolean;
    /**
     *
     * @type {Array<CompletionItem>}
     * @memberof CompletionList
     */
    'items': Array<CompletionItem>;
}
