/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ComputerUseStatusResponse
 */
export interface ComputerUseStatusResponse {
    /**
     * Status of computer use services (active, partial, inactive, error)
     * @type {string}
     * @memberof ComputerUseStatusResponse
     */
    'status': ComputerUseStatusResponseStatusEnum;
}
export declare const ComputerUseStatusResponseStatusEnum: {
    readonly ACTIVE: "active";
    readonly PARTIAL: "partial";
    readonly INACTIVE: "inactive";
    readonly ERROR: "error";
};
export type ComputerUseStatusResponseStatusEnum = typeof ComputerUseStatusResponseStatusEnum[keyof typeof ComputerUseStatusResponseStatusEnum];
