/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OrganizationRole
 */
export interface OrganizationRole {
    /**
     * Role ID
     * @type {string}
     * @memberof OrganizationRole
     */
    'id': string;
    /**
     * Role name
     * @type {string}
     * @memberof OrganizationRole
     */
    'name': string;
    /**
     * Role description
     * @type {string}
     * @memberof OrganizationRole
     */
    'description': string;
    /**
     * Roles assigned to the user
     * @type {Array<string>}
     * @memberof OrganizationRole
     */
    'permissions': Array<OrganizationRolePermissionsEnum>;
    /**
     * Global role flag
     * @type {boolean}
     * @memberof OrganizationRole
     */
    'isGlobal': boolean;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof OrganizationRole
     */
    'createdAt': Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof OrganizationRole
     */
    'updatedAt': Date;
}
export declare const OrganizationRolePermissionsEnum: {
    readonly WRITE_REGISTRIES: "write:registries";
    readonly DELETE_REGISTRIES: "delete:registries";
    readonly WRITE_SNAPSHOTS: "write:snapshots";
    readonly DELETE_SNAPSHOTS: "delete:snapshots";
    readonly WRITE_SANDBOXES: "write:sandboxes";
    readonly DELETE_SANDBOXES: "delete:sandboxes";
    readonly READ_VOLUMES: "read:volumes";
    readonly WRITE_VOLUMES: "write:volumes";
    readonly DELETE_VOLUMES: "delete:volumes";
    readonly WRITE_REGIONS: "write:regions";
    readonly DELETE_REGIONS: "delete:regions";
    readonly READ_RUNNERS: "read:runners";
    readonly WRITE_RUNNERS: "write:runners";
    readonly DELETE_RUNNERS: "delete:runners";
    readonly READ_AUDIT_LOGS: "read:audit_logs";
};
export type OrganizationRolePermissionsEnum = typeof OrganizationRolePermissionsEnum[keyof typeof OrganizationRolePermissionsEnum];
