/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare const SnapshotState: {
    readonly BUILDING: "building";
    readonly PENDING: "pending";
    readonly PULLING: "pulling";
    readonly ACTIVE: "active";
    readonly INACTIVE: "inactive";
    readonly ERROR: "error";
    readonly BUILD_FAILED: "build_failed";
    readonly REMOVING: "removing";
};
export type SnapshotState = typeof SnapshotState[keyof typeof SnapshotState];
