"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEvent = void 0;
/**
 * The type of event being sent
 * @export
 * @enum {string}
 */
exports.WebhookEvent = {
    SANDBOX_CREATED: 'sandbox.created',
    SANDBOX_STATE_UPDATED: 'sandbox.state.updated',
    SNAPSHOT_CREATED: 'snapshot.created',
    SNAPSHOT_STATE_UPDATED: 'snapshot.state.updated',
    SNAPSHOT_REMOVED: 'snapshot.removed',
    VOLUME_CREATED: 'volume.created',
    VOLUME_STATE_UPDATED: 'volume.state.updated'
};
//# sourceMappingURL=webhook-event.js.map